name: macOS 10.15

on:
  pull_request:
    branches: [ main ]

jobs:
  hardware:
    name: Hardware
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: pip2 install future
      - run: brew install --cask kicad
      - run: ./blocks/audio-in-daisy/build.py
      - run: ./blocks/audio-out-daisy/build.py
      - run: ./blocks/button/build.py
      - run: ./blocks/cv-in/build.py
      - run: ./blocks/gate-in/build.py
      - run: ./blocks/gate-out/build.py
      - run: ./blocks/led/build.py
      - run: ./blocks/led-bi/build.py
      - run: ./blocks/multiplexer/build.py
      - run: ./blocks/pot/build.py
      - run: ./blocks/power-bus/build.py
      - run: ./blocks/regulator-daisy/build.py
      - run: ./blocks/slider/build.py
      - run: ./blocks/switch/build.py
      - run: ./blocks/trim/build.py
      - run: ./blocks/kits/stats.py
      - run: ./blocks/kits/build.py

  software:
    name: Software
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: brew install armmbed/formulae/arm-none-eabi-gcc
      - run: brew install ninja
      - run: python3 blocks/test/configure.py
      - run: python3 blocks/test/build.py

  software_py2:
    name: Software (Python 2 Compat)
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: pip2 install future
      - run: brew install armmbed/formulae/arm-none-eabi-gcc
      - run: brew install ninja
      - run: python2 blocks/test/configure.py
      - run: python2 blocks/test/build.py

  unit_tests:
    name: Unit Tests
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: brew install ninja
      - run: python3 test/configure.py
      - run: python3 test/build.py
      - run: python3 test/run.py

  unit_tests_py2:
    name: Unit Tests (Python 2 Compat)
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: pip2 install future
      - run: brew install ninja
      - run: python2 test/configure.py
      - run: python2 test/build.py
      - run: python2 test/run.py

