name: Ubuntu 20.04

on:
  pull_request:
    branches: [ main ]

jobs:
  hardware:
    name: Hardware
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: sudo apt-get update
      - run: sudo apt-get install kicad
      - run: python audio-in-daisy/build.py
      - run: python audio-out-daisy/build.py
      - run: python button/build.py
      - run: python cv-in/build.py
      - run: python gate-in/build.py
      - run: python gate-out/build.py
      - run: python led/build.py
      - run: python led-bi/build.py
      - run: python multiplexer/build.py
      - run: python pot/build.py
      - run: python power-bus/build.py
      - run: python regulator-daisy/build.py
      - run: python slider/build.py
      - run: python switch/build.py
      - run: python trim/build.py
      - run: python kits/stats.py
      - run: python kits/build.py

  software:
    name: Software
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: sudo apt-get update
      - run: sudo apt-get install gcc-arm-none-eabi
      - run: sudo apt-get install -y ninja-build
      - run: python test/configure.py
      - run: python test/build.py

  software_py2:
    name: Software (Python 2 Compat)
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: sudo apt-add-repository universe
      - run: sudo apt-get update
      - run: sudo apt install python2
      - run: curl https://bootstrap.pypa.io/get-pip.py --output get-pip.py
      - run: sudo python2 get-pip.py
      - run: pip2 install future
      - run: sudo apt-get install gcc-arm-none-eabi
      - run: sudo apt-get install -y ninja-build
      - run: python2 test/configure.py
      - run: python2 test/build.py
