name: Windows 2019

on:
  pull_request:
    branches: [ main ]

jobs:
  software_cpp:
    name: Software C++
    runs-on: windows-2019
    defaults:
      run:
        shell: bash -l {0} # Source profile for each step
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: python3 build-system/install.py
      - run: erbb setup
      - name: test/data
        run: erbb configure && erbb build && erbb build simulator && erbb build hardware
        working-directory: test/data
      - name: samples/bypass
        run: erbb configure && erbb build && erbb build simulator && erbb build hardware
        working-directory: samples/bypass
      - name: samples/drop
        run: erbb configure && erbb build && erbb build simulator && erbb build hardware
        working-directory: samples/drop
      - name: samples/reverb
        run: erbb configure && erbb build && erbb build simulator && erbb build hardware
        working-directory: samples/reverb
      - name: samples/kick
        run: erbb configure && erbb build && erbb build simulator && erbb build hardware
        working-directory: samples/kick
      - name: erbb init
        run: mkdir init && cd init && erbb init Init && erbb configure && erbb build && erbb build simulator && erbb build hardware
        working-directory: samples

  software_max:
    name: Software Max/MSP/Gen~
    runs-on: windows-2019
    defaults:
      run:
        shell: bash -l {0} # Source profile for each step
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: python3 build-system/install.py
      - run: erbb setup
      - name: test/max
        run: erbb configure && erbb build simulator && erbb build && erbb build hardware
        working-directory: test/max
      - name: test/max2
        run: erbb configure && erbb build simulator && erbb build && erbb build hardware
        working-directory: test/max2
